CREATE DATABASE ELIOT_DB;
GO
USE ELIOT_DB;

CREATE TABLE Races (
	idRace INT IDENTITY(1,1) 
	CONSTRAINT PK_Races PRIMARY KEY,
	nom VARCHAR(50) CONSTRAINT UQ_Races_nom UNIQUE
);

CREATE TABLE Personnages (
	idPersonnage INT IDENTITY(1,1)
	CONSTRAINT PK_Personnages PRIMARY KEY,
	nomPersonnage VARCHAR(50) NOT NULL,
	dateNaissance DATE NOT NULL,
	race INT NOT NULL
	CONSTRAINT FK_Personnages_Races 
	FOREIGN KEY REFERENCES Races(idRace)
);